credentials:
  usernames:
    moe:
      name: Dr. Almikhlafi
      password: '$2b$12$M3dZSx/0HTfO3CCi30uK.uMK3UXwl//sMUxuId3YLssTuo.Uz4SG.'
    czarina:
      name: RN
      password: '$2b$12$1H.sbKURI1qscBuyzzbe8uRM6br.A8q4P9w.NKt35hfIbeZMI9R4O'

cookie:
  name: clinic_app
  key: abcdef
  expiry_days: 1

preauthorized:
  emails: []
